ipwhitelist: [192.168.0.0,192.168.0.1]
ipblacklist: [192.168.1.0,192.168.1.1]
timeout: 3000
apilist:
grouplist:
updatetime: 2018-01-01 10:00:00
createtime: 2018-01-01 09:00:00
status: on
apiconfigpath:  config/api/api_info.yml
strategyconfigpath: config/strategy/strategy_info.yml
strategylist: