apiinfo:
  - apiname: 新增网关1
    requesturl: /GateWay/Add
    methodtype: GET
    groupname: 网关组1
    groupid: 1001
    status: on
  - apiname: 新增网关2
    requesturl: /GateWay/Add
    methodtype: GET
    groupname: 网关组1
    groupid: 1001
    status: on
